blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *


app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('blog_single/<int:post_id>',blog_single,name='blog_single'),
    path('category/<str:cat_name>',blog_view,name='blog_cate'),
    path('author/<str:author_username>',blog_view,name='blog_author'),
    path('search/',blog_search,name='blog_search'),
    
    path('test/<str:name>',test)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
import website.views



urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/', include('accounts.urls'))
    # path('accounts/', include('django.contrib.auth.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = website.views.handler404
handler500 = website.views.handler500

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *
from django.contrib.sitemaps.views import sitemap
from  website.sitemaps import WebsiteStaticSitemap
from blog.sitemaps import BlogSitemap
from django.urls import include
from django.urls import re_path
from django.views.generic import TemplateView


app_name = 'website'
sitemaps = {
    'static': WebsiteStaticSitemap,
    'blog':BlogSitemap
    
}

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('news_letter/',news_letter,name='news_letter'),
    path(
    "sitemap.xml",sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt',include('robots.urls')),
    

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

# urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='commingsoon.html'), name='maintenance'))

blog/models.py
from django.db import models
import datetime
from time import timezone
from django.contrib.auth.models import User
# from accounts.models import CustomUser 
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name =models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.name
    
class Post(models.Model):
    author = models.ForeignKey(User,models.SET_NULL,null=True)
    title = models.CharField(max_length=200)
    content = models.TextField()
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=0)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category)
    login_require = models.BooleanField(default=False)
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:blog_single',kwargs={'post_id':self.id})

blog/views.py
from django.shortcuts import render,get_object_or_404
from blog.models import Post
import datetime
from django.http import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

# Create your views here.
def blog_view(request,**kwargs):
    posts = Post.objects.filter(published_date__lte= timezone.now(),status=1)
   

    if kwargs.get('cat_name')!=None:
        posts =posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username')!=None:
        posts = posts.filter(author__username=kwargs['author_username'])


    try:
        page_number =  request.GET.get('page')        
        paginator = Paginator(posts,3)
        page_obj = paginator.get_page(page_number)   

    except EmptyPage:
        page_obj = paginator.get_page(1) 
    except PageNotAnInteger:
        page_obj = paginator.get_page(1) 
        
        
    return render(request,'blog-home.html',{'posts':page_obj})



def blog_single(request,post_id):
    post = get_object_or_404(Post,id=post_id,status = 1,published_date__lte= timezone.now())
    post.counted_view +=1
    post.save()
    prev_post = Post.objects.filter(id__lt=post_id,status=1,published_date__lte= timezone.now()
                                 ).order_by('-id')
    
    next_post = Post.objects.filter(id__gt=post_id,status=1,published_date__lte= timezone.now()
                                 ).order_by('id')
    

    if len(prev_post):
        prev_post = prev_post[0]

    if len(next_post):
        next_post = next_post[0]

    content = {"prev_post":prev_post,"next_post":next_post,'post':post}
    return render(request,'blog-single.html',content)

def blog_search(request):
    posts = Post.objects.filter(published_date__lte= timezone.now(),status=1)
    if request.method == 'GET':
        if s:=request.GET.get('s'):
            posts =posts.filter(content__contains=s)
        
    return render(request,'blog-home.html',{'posts':posts})


def test(request,name):
    return HttpResponse(name)

blog/templates/blog-ads-widget.html
{%load static%}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

blog/templates/blog-home.html
{%extends 'base.html'%}
{% load static %}
{% load blog_tags%}
{%block content%}
				<!-- start banner Area -->
			<section class="banner-area relative blog-home-banner" id="home">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content blog-header-content col-lg-12">
							<h1 class="text-white">
								Dude You’re Getting
								a Telescope				
							</h1>	
							<p class="text-white">
								There is a moment in the life of any aspiring astronomer that it is time to buy that first
							</p>							
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->				  

			<!-- Start top-category-widget Area -->
			<section class="top-category-widget-area pt-90 pb-90 ">
				<div class="container">
					<div class="row">		
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Social life</h4>
								        <span></span>								        
								        <p>Enjoy your social life together</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Politics</h4>
								        <span></span>								        
								        <p>Be a part of politics</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>
						<div class="col-lg-4">
							<div class="single-cat-widget">
								<div class="content relative">
									<div class="overlay overlay-bg"></div>
								    <a href="#" target="_blank">
								      <div class="thumb">
								  		 <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
								  	  </div>
								      <div class="content-details">
								        <h4 class="content-title mx-auto text-uppercase">Food</h4>
								        <span></span>
								        <p>Let the food be finished</p>
								      </div>
								    </a>
								</div>
							</div>
						</div>												
					</div>
				</div>	
			</section>
			<!-- End top-category-widget Area -->
			
			<!-- Start post-content Area -->
			<section class="post-content-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							{% for post in posts%}
							<div class="single-post row">
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li>
											<a href="{% url 'blog:blog_cate' cat.name %}">{{cat.name}}
												{% if not forloop.last %}
													,
												{% endif %}
												</a>
										</li>
										{%endfor%}
										
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url 'blog:blog_author' post.author.username%}">{{post.author.first_name}} {{post.author.last_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.updated_date|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>						
									</div>
								</div>
								<div class="col-lg-9 col-md-9 ">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>
									<a class="posts-title" href="{% url 'blog:blog_single' post.id %}"><h3>{{post.title}}</h3></a>
									<p class="excert">
										{{post.content|truncatewords:3}}
									</p>
									<a href="{% url 'blog:blog_single' post.id %}" class="primary-btn">View More</a>
								</div>
							</div>
							{% endfor %}
																					
		                    <nav class="blog-pagination justify-content-center d-flex">
								
		                        <ul class="pagination">
									{% if posts.has_previous %}
									<li class="page-item">
		                                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
								    {% endif %}
									{% for p in posts.paginator.page_range %}
										{% if posts.number != p%}
											<li class="page-item">
												<a href="?page={{p}}" class="page-link">{{p}}</a></li>
										{%else%}
											<li class="page-item active">
												<a href="?page={{p}}" class="page-link">{{p}}</a></li>
										{%endif%}
									{%endfor%}
		                            {% if posts.has_next %}
									<li class="page-item">
		                                <a href="?page={{ posts.paginator.num_pages }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
										
									{% endif %}
									
		                        </ul>
		                    </nav>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								
								{% include 'blog-search.html' %}
								{% include 'blog-writer.html' %}
								{% latest_post %}
								{% include 'blog-ads-widget.html' %}
								{% post_categories %}
								{% include 'blog-newsletter.html'%}
								{% include 'blog-tag-clouds.html'%}							
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
{%endblock%}

blog/templates/blog-latest-post.html
{% load static%}
{% load humanize%}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
        {% for post in posts%}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" style="width: 100px;height:60px;" src="{{post.image.url}}" alt="">
            </div>
            <div class="details">
                <a href="{% url 'blog:blog_single' post.id%}"><h6>{{post.title}}</h6></a>
                <p> {{post.published_date|naturaltime}} </p>
            </div>
        </div>
        {%endfor%}
        														
    </div>
</div>

blog/templates/blog-newsletter.html
<div class="single-sidebar-widget newsletter-widget">
    <h4 class="newsletter-title">Newsletter</h4>
    <p>
        Here, I focus on a range of items and features that we use in life without
        giving them a second thought.
    </p>
    <div class="form-group d-flex flex-row">
       <div class="col-autos">
          <div class="input-group">
            <div class="input-group-prepend">
              <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
            </div>
            </div>
            <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" >
          </div>
        </div>
        <a href="#" class="bbtns">Subcribe</a>
    </div>	
    <p class="text-bottom">
        You can unsubscribe at any time
    </p>								
</div>

blog/templates/blog-post-categories.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
       {% for key,value in cats_posts.items%}
       <li>
        
        <a href="{% url 'blog:blog_cate' key %}" class="d-flex justify-content-between">
            <p>{{key}}</p>
            <p>{{value}}</p>
        </a>
       </li>
       {%endfor%} 
       														
    </ul>
</div>	

blog/templates/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:blog_search'%}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

blog/templates/blog-single.html
{%extends 'base.html'%}
{% load static %}
{%load blog_tags%}
{%block content%}
				<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								{{post.title}}				
							</h1>	
							<p class="text-white link-nav">
								<a href="{% url 'website:index' %}">Home </a> 
								 <span class="lnr lnr-arrow-right"></span>
								 <a href="{% url 'blog:index'%}">Blog </a> <span class="lnr lnr-arrow-right"></span> {{post.title}}</p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->					  
			
			<!-- Start post-content Area -->
			<section class="post-content-area single-post-area">
				<div class="container">
					<div class="row">
						<div class="col-lg-8 posts-list">
							<div class="single-post row">
								<div class="col-lg-12">
									<div class="feature-img">
										<img class="img-fluid" src="{{post.image.url}}" alt="">
									</div>									
								</div>
								<div class="col-lg-3  col-md-3 meta-details">
									<ul class="tags">
										{% for cat in post.category.all %}
										<li>
											<a href="{% url 'blog:blog_cate' cat.name %}">{{cat}}
												{% if not forloop.last %}
													,
												{% endif %}
												</a>
										</li>

										{%endfor%}
									</ul>
									<div class="user-details row">
										<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.first_name}} {{post.author.last_name}}</a> <span class="lnr lnr-user"></span></p>
										<p class="date col-lg-12 col-md-12 col-6"><a href="#"> {{post.updated_date|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
										<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} Views</a> <span class="lnr lnr-eye"></span></p>
										<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span class="lnr lnr-bubble"></span></p>
										<ul class="social-links col-lg-12 col-md-12 col-6">
											<li><a href="#"><i class="fa fa-facebook"></i></a></li>
											<li><a href="#"><i class="fa fa-twitter"></i></a></li>
											<li><a href="#"><i class="fa fa-github"></i></a></li>
											<li><a href="#"><i class="fa fa-behance"></i></a></li>
										</ul>																				
									</div>
								</div>
								<div class="col-lg-9 col-md-9">
									<h3 class="mt-20 mb-20">{{post.title}}</h3>
									<p class="excert">
									{{post.content|safe}}
									</p>
								</div>
							</div>
							<div class="navigation-area">
								<div class="row">
									
									<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
										{% if prev_post %}
										<div class="thumb">
											<a href="{% url 'blog:blog_single' prev_post.id%}"><img class="img-fluid" style="width: 60px;height: 60px;" src="{{prev_post.image.url}}" alt=""></a>
										</div>
										<div class="arrow">
											<a href="{% url 'blog:blog_single' prev_post.id%}"><span class="lnr text-white lnr-arrow-left"></span></a>
										</div>
										<div class="detials">
											<p>Prev Post</p>
											<a href="{% url 'blog:blog_single' prev_post.id%}"><h4>{{prev_post.title}}</h4></a>
										</div>
									{% endif %}
									</div>
									<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
										{% if next_post %}
										<div class="detials">
											<p>Next Post</p>
											<a href="{% url 'blog:blog_single' next_post.id%}"><h4>{{next_post.title}}</h4></a>
										</div>
										<div class="arrow">
											<a href="{% url 'blog:blog_single' next_post.id%}"><span class="lnr text-white lnr-arrow-right"></span></a>
										</div>
										<div class="thumb">
											<a href="{% url 'blog:blog_single' next_post.id%}"><img class="img-fluid" style="width: 60px;height: 60px;" src="{{next_post.image.url}}" alt=""></a>
										</div>
										{% endif %}										
									</div>									
								</div>
							</div>
							<div class="comments-area">
								<h4>05 Comments</h4>
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c1.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">Emilly Blunt</a></h5>
                                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                                <p class="comment">
                                                    Never say goodbye till the end comes!
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
                                    </div>
                                </div>	
								<div class="comment-list left-padding">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c2.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">Elsie Cunningham</a></h5>
                                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                                <p class="comment">
                                                    Never say goodbye till the end comes!
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
                                    </div>
                                </div>	
								<div class="comment-list left-padding">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c3.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">Annie Stephens</a></h5>
                                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                                <p class="comment">
                                                    Never say goodbye till the end comes!
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
                                    </div>
                                </div>	
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c4.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">Maria Luna</a></h5>
                                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                                <p class="comment">
                                                    Never say goodbye till the end comes!
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
                                    </div>
                                </div>	
								<div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'img/blog/c5.jpg' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">Ina Hayes</a></h5>
                                                <p class="date">December 4, 2017 at 3:12 pm </p>
                                                <p class="comment">
                                                    Never say goodbye till the end comes!
                                                </p>
                                            </div>
                                        </div>
                                        <div class="reply-btn">
                                               <a href="" class="btn-reply text-uppercase">reply</a> 
                                        </div>
                                    </div>
                                </div>	                                             				
							</div>
							<div class="comment-form">
								<h4>Leave a Comment</h4>
								<form>
									<div class="form-group form-inline">
									  <div class="form-group col-lg-6 col-md-12 name">
									    <input type="text" class="form-control" id="name" placeholder="Enter Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
									  </div>
									  <div class="form-group col-lg-6 col-md-12 email">
									    <input type="email" class="form-control" id="email" placeholder="Enter email address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
									  </div>										
									</div>
									<div class="form-group">
										<input type="text" class="form-control" id="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
									</div>
									<div class="form-group">
										<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
									</div>
									<a href="#" class="primary-btn text-uppercase">Post Comment</a>	
								</form>
							</div>
						</div>
						<div class="col-lg-4 sidebar-widgets">
							<div class="widget-wrap">
								<div class="single-sidebar-widget search-widget">
									<form class="search-form" action="#">
			                            <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" >
			                            <button type="submit"><i class="fa fa-search"></i></button>
			                        </form>
								</div>
							    {% include 'blog-writer.html' %}
								{% latest_post %}
								{% include 'blog-ads-widget.html' %}
								{% post_categories %}
								{% include 'blog-newsletter.html'%}
								{% include 'blog-tag-clouds.html'%}								
							</div>
						</div>
					</div>
				</div>	
			</section>
			<!-- End post-content Area -->
	{%endblock%}

blog/templates/blog-tag-clouds.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        <li><a href="#">Technology</a></li>
        <li><a href="#">Fashion</a></li>
        <li><a href="#">Architecture</a></li>
        <li><a href="#">Fashion</a></li>
        <li><a href="#">Food</a></li>
        <li><a href="#">Technology</a></li>
        <li><a href="#">Lifestyle</a></li>
        <li><a href="#">Art</a></li>
        <li><a href="#">Adventure</a></li>
        <li><a href="#">Food</a></li>
        <li><a href="#">Lifestyle</a></li>
        <li><a href="#">Adventure</a></li>
    </ul>
</div>	

blog/templates/blog-writer.html
{%load static%}

<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>Charlie Barber</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>