accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('login/',login_view,name='login_view'),
    path('logout/',logout_view,name='logout_view'),
    path('signup/',signup_view,name='signup_view'),
    
    
    # 1) enter email address to send email 
    path('password_reset/', auth_views.PasswordResetView
        .as_view(template_name="password-reset.html",
                email_template_name = 'password_reset_confirm.html',
                success_url = 'done/'), 
        name='password_reset'),
    #2) show successfull message to sent email
     path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name="password_reset_done",
    ),
    
    # 3) email link clicked 
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name=
                                                    'password_reset_new.html',
                                                    success_url= '/accounts/reset/done/'),
        name="password_reset_confirm"
    ),
    # 4) password changed message
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'),
        name="password_reset_complete",
    ),
     


    

    
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *


app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('blog_single/<int:post_id>',blog_single,name='blog_single'),
    path('category/<str:cat_name>',blog_view,name='blog_cate'),
    path('author/<str:author_username>',blog_view,name='blog_author'),
    path('search/',blog_search,name='blog_search'),
    
    path('test/<str:name>',test)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
import website.views



urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/', include('accounts.urls'))
    # path('accounts/', include('django.contrib.auth.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = website.views.handler404
handler500 = website.views.handler500

accounts/models.py
# from django.db import models

# # Create your models here.
# from django.contrib.auth.models import User
# from django.db import models

# class CustomUser(User):
#     email = models.EmailField(unique=True)

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    email = forms.EmailField(label='Email')
    class Meta:
        model = User
        fields = ("username",'email',  "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = False

    def clean(self) -> dict[str, Any]:
        cd = self.cleaned_data
        username = cd.get('username')
        if '@' in username:
            kwargs = {'email': username}
        else:
            kwargs = {'username': username}
      
        return cd
        # email =   cd.get('email')
        # if User.objects.filter(email=email).count():
        #     self.add_error('email', "email address already exists!")

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')

    class Meta:
        model = User
        unique_together = ('email',)
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        email = self.cleaned_data["email"]
        user.email = email
        if commit:
            user.save()
        return user
    def clean(self) -> dict[str, Any]:
        cd = self.cleaned_data
        email =   cd.get('email').lower()
        if User.objects.filter(email=email).count():
            self.add_error('email', "email address already exists!")

            
        return cd

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from accounts.utils import CustomBackend
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from accounts.forms import CustomAuthenticationForm,CustomUserCreationForm
from django.contrib.auth.forms import PasswordChangeForm,PasswordResetForm


# Create your views here.
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomAuthenticationForm(request=request,data = request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                print(username)
                user = CustomBackend.authenticate(request,username=username,password = password)
                if user is not None:
                    login(request,user)
                    messages.add_message(request,messages.SUCCESS,f'welcom, {username}')
                    return redirect('/')
                else:
                    messages.add_message(request,messages.ERROR,'this user is not exist!')

            
            else:
                print(form.errors)
                add_err(request,form.errors)              

        return render(request,'login.html')
    return redirect('/')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def add_err(request,form_err):
    err = form_err.items()
    for key,vals in err:
        for v in vals:
            messages.add_message(request,messages.ERROR,key+': '+v)

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method=='POST':
            form = CustomUserCreationForm(request.POST)
            
            if form.is_valid():
                form.save()
                messages.add_message(request,messages.SUCCESS,f'registeration completed!')
                return redirect(reverse('accounts:login_view'))
            
            print(form.errors)
            add_err(request,form.errors)

            return render(request,'register.html',{'form':form})
        
        form = CustomUserCreationForm()
        # print(form)
        return render(request,'register.html',{'form':form})
    return redirect('/')


def pass_reset_view(request):
    form =PasswordResetForm()
    return render(request,'password-reset.html',{'form':form})

accounts/templates/account-base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>Login 10</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="img js-fullheight" style="background-image: url({% static 'imgs/bg.jpg.webp' %});">
    <section class="ftco-section">
        <div class="container">
            {% if messages %}
				{% for message in messages %}
				{% if message.tags == 'error' %}
				<div style="z-index: 1000;"   class="alert alert-danger alert-dismissible fade show" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</div>
				{%else%}
				<div style="z-index: 1000;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</div>
				{%endif%}
                {% endfor %}
			{%endif%}
            <div class="row justify-content-center">
                {% block content %}
            {% endblock %}


        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script defer
    src="https://static.cloudflareinsights.com/beacon.min.{% static 'js/vcd15cbe7772f49c399c6a5babf22c1241717689176015"
    integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ=="
    data-cf-beacon='{"rayId":"8b4b46ead8b56704","serverTiming":{"name":{"cfL4":true}},"version":"2024.7.0","token":"cd0b4b3a733644fc843ef0b185f98241"}'
    crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/login.html
{%extends 'account-base.html'%}
{%block content %}
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center"> Login </h3>
                        <form action="{% url 'accounts:login_view'%}" method="post" class="signin-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input name="username" type="text" class="form-control" placeholder="Username or Email" required>
                            </div>
                            <div class="form-group">
                                <input name="password" id="password-field" type="password" class="form-control" placeholder="Password"
                                    required>
                                <span toggle="#password-field"
                                    class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:password_reset'%}" style="color: #fff">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
{% endblock%}
            

accounts/templates/password-reset.html
{%extends 'account-base.html'%}
{% block content %}
<div class="col-md-6 col-lg-4">
    <div class="login-wrap p-0">
        <h3 class="mb-4 text-center"> Reset Password </h3>
        <form method="post" class="signin-form">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" name="email" autocomplete="email" 
                maxlength="254" class="form-control" required="" 
                placeholder="Email">  
              
            </div>

            <div class="form-group">
                <button type="submit" class="form-control btn btn-primary submit px-3">Reset Password</button>
            </div>
            
        </form>
        
    </div>
</div>
 
{% endblock content %}

accounts/templates/password_reset_complete.html
{%extends 'account-base.html'%}
{% block content %}
    <div class="alert alert-info">
        Your password has been set.
        <a href="{% url 'accounts:login_view' %}" style="color:#007bff">Sign In Here</a>
    </div>
    
{% endblock content %}

accounts/templates/password_reset_confirm.html
{% load i18n %}
{% autoescape off %}
	{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}
	
	{% translate "Please go to the following page and choose a new password:" %}
	{% block reset_link %}
	{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
	{% endblock %}
	{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
	
	{% translate "Thanks for using our site!" %}
	
	{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}
	{% endautoescape %}
    <p>this is a test</p>

accounts/templates/password_reset_done.html
{%extends 'account-base.html'%}
{% block content %}

    <div class="alert alert-info">
        <p> We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
 
        <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

        </p>
    </div>
{% endblock content %}

accounts/templates/password_reset_new.html
{%extends 'account-base.html'%}
{% load i18n static %}

{% block content %}

{% if validlink %}
<div class="col-md-6 col-lg-4">
    <div class="login-wrap p-0">
        <h3 class="mb-4 text-center"> Change Password </h3>
        <form  method="post" class="signin-form">
            <input hidden autocomplete="username" value="{{ form.user.get_username }}">

            {% csrf_token %}
            <div class="form-group">
                <input name="new_password1" id="password-field" type="password" class="form-control" placeholder="New password"
                required>
                <span toggle="#password-field"
                class="fa fa-fw fa-eye field-icon toggle-password"></span> 
                {{ form.new_password1.errors }}
 
            </div>
            <div class="form-group">
                <input name="new_password2" id="password-field" type="password" class="form-control" placeholder="Confirm Password"
                    required>
                <span toggle="#password-field"
                    class="fa fa-fw fa-eye field-icon toggle-password"></span>
                    {{ form.new_password2.errors }}
            </div>
            <div class="form-group">
                <button type="submit" class="form-control btn btn-primary submit px-3"> Change my password</button>
            </div>
            
        </form>
        
    </div>
</div>
{% else %}
<p>{% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}
{% endblock content %}

accounts/templates/register.html
{%extends 'account-base.html'%}
{%block content %}
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        <h3 class="mb-4 text-center">Register</h3>
                        <form action="{% url 'accounts:signup_view'%}" method="post" class="signin-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input name="username" type="text" class="form-control" placeholder="Username" required>
                            </div>
                            <div class="form-group">
                                <input name="email" type="text" class="form-control" placeholder="Email" required>
                            </div>
                            <div class="form-group">
                                <input name="password1" id="password-field" type="password" class="form-control" placeholder="Password"
                                    >
                                <span toggle="#password-field"
                                    class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <input name="password2" id="password-field" type="password" class="form-control" placeholder="Confirm password"
                                    >
                                <span toggle="#password-field"
                                    class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                            </div>
                            
                        </form>
                        
                    </div>
                </div>
{% endblock%}
            