accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import *
from django.contrib.auth import views as auth_views
from django.urls import reverse

app_name = 'accounts'
urlpatterns = [
    path('login/',login_view,name='login_view'),
    path('logout/',logout_view,name='logout_view'),
    path('signup/',signup_view,name='signup_view'),
    
    
    # 1) enter email address to send email 
    path('password_reset/', auth_views.PasswordResetView
        .as_view(template_name="password-reset.html",
                email_template_name = 'password_reset_confirm.html',
                success_url = 'done/'), 
        name='password_reset'),
    #2) show successfull message to sent email
     path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name="password_reset_done",
    ),
    
    # 3) email link clicked 
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name=
                                                    'password_reset_new.html',
                                                    success_url= '/accounts/reset/done/'),
        name="password_reset_confirm"
    ),
    # 4) password changed message
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name = 'password_reset_complete.html'),
        name="password_reset_complete",
    ),
     


    

    
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog.views import *


app_name = 'blog'
urlpatterns = [
    path('',blog_view,name='index'),
    path('blog_single/<int:post_id>',blog_single,name='blog_single'),
    path('category/<str:cat_name>',blog_view,name='blog_cate'),
    path('author/<str:author_username>',blog_view,name='blog_author'),
    path('search/',blog_search,name='blog_search'),
    
    path('test/<str:name>',test)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404
import website.views



urlpatterns = [
    path('admin/',admin.site.urls),
    path('', include('website.urls')),
    path('blog/',include('blog.urls')),
    path('accounts/', include('accounts.urls'))
    # path('accounts/', include('django.contrib.auth.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = website.views.handler404
handler500 = website.views.handler500

website/urls.py
from django.contrib import admin
from django.urls import path
from website.views import *
from django.contrib.sitemaps.views import sitemap
from  website.sitemaps import WebsiteStaticSitemap
from blog.sitemaps import BlogSitemap
from django.urls import include
from django.urls import re_path
from django.views.generic import TemplateView


app_name = 'website'
sitemaps = {
    'static': WebsiteStaticSitemap,
    'blog':BlogSitemap
    
}

urlpatterns = [
    path('',index,name='index'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('news_letter/',news_letter,name='news_letter'),
    path(
    "sitemap.xml",sitemap,{"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt',include('robots.urls')),
    

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

# urlpatterns.insert(0, re_path(r'^', TemplateView.as_view(template_name='commingsoon.html'), name='maintenance'))

website/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name= models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255,null=True,blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    updated_date = models.DateTimeField(auto_now_add=True)


class NewsLetter(models.Model):
    email = models.EmailField()

website/forms.py
from django import forms
from website.models import Contact,NewsLetter
from captcha.fields import CaptchaField



class ContactForm(forms.ModelForm):
    captcha = CaptchaField()
    # captcha = ReCaptchaField()

    class Meta:
        model = Contact
        fields = '__all__'


class NewsLetterForm(forms.ModelForm):
    
    captcha = CaptchaField()
    class Meta:
        model = NewsLetter
        fields = '__all__'

website/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from website.forms import ContactForm,NewsLetterForm
from django.contrib import messages
from website.models import Contact
from django.template import Context, loader


def index(request):
    return render(request,'index.html')

def about(request):
    return render(request,'about.html')


def contact(request):
    if request.method == 'POST':
        form = ContactForm(data = request.POST)
        
        if form.is_valid():
            new_contact = form.save(commit=False)
            new_contact.name = 'anonymous' 
            new_contact.save()
            
            messages.add_message(request,messages.SUCCESS,'your ticket submitted successfully!')
        else:
            messages.add_message(request,messages.ERROR,'please check your input format')


    form = ContactForm()
    return render(request,'contact.html',{'form':form})

def news_letter(request):
    if request.method == 'POST':
        form = NewsLetterForm(data = request.POST)
        if form.is_valid():
            form.save()
    return HttpResponseRedirect('/')



def handler404(request, exception, template_name="404.html"):
    return render(request,'404.html',status=404)

def handler500(request,*args, **argv):
    return render(request,'500.html',status=500)

website/templates/about.html
{% extends 'base.html' %}    
{% load static %}
{% block content%}
			<!-- start banner Area -->
			<section class="about-banner relative">
				<div class="overlay overlay-bg"></div>
				<div class="container">				
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								About Us				
							</h1>	
							<p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="about.html"> About Us</a></p>
						</div>	
					</div>
				</div>
			</section>
			<!-- End banner Area -->	

			<!-- Start about-info Area -->
			<section class="about-info-area section-gap">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 info-left">
							<img class="img-fluid" src="{% static 'img/about/info-img.jpg' %}" alt="">
						</div>
						<div class="col-lg-6 info-right">
							<h6>About Us</h6>
							<h1>Who We Are?</h1>
							<p>
								Here, I focus on a range of items and features that we use in life without giving them a second thought. such as Coca Cola. Dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.
							</p>
						</div>
					</div>
				</div>	
			</section>
			<!-- End about-info Area -->
			
			<!-- Start other-issue Area -->
			<section class="other-issue-area section-gap">
				<div class="container">
		            <div class="row d-flex justify-content-center">
		                <div class="menu-content pb-70 col-lg-9">
		                    <div class="title text-center">
		                        <h1 class="mb-10">Other issues we can help you with</h1>
		                        <p>We all live in an age that belongs to the young at heart. Life that is.</p>
		                    </div>
		                </div>
		            </div>					
					<div class="row">
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="">					
								</div>
								<a href="#">
									<h4>Rent a Car</h4>
								</a>
								<p>
									The preservation of human life is the ultimate value, a pillar of ethics and the foundation.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="">					
								</div>
								<a href="#">
									<h4>Cruise Booking</h4>
								</a>
								<p>
									I was always somebody who felt quite sorry for myself, what I had not got compared.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="">					
								</div>
								<a href="#">
									<h4>To Do List</h4>
								</a>
								<p>
									The following article covers a topic that has recently moved to center stage–at least it seems.
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6">
							<div class="single-other-issue">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="">					
								</div>
								<a href="#">
									<h4>Food Features</h4>
								</a>
								<p>
									There are many kinds of narratives and organizing principles. Science is driven by evidence.
								</p>
							</div>
						</div>																		
					</div>
				</div>	
			</section>
			<!-- End other-issue Area -->
{% endblock%}

website/templates/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Travel</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
        <!--
        CSS
        ============================================= -->
		{% compress css %}

        <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">				
        <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">							
        <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">				
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
		{% endcompress %}


    </head>

		<body>	
			<header id="header">
				<div class="header-top">
					<div class="container">
						{% if messages %}
				{% for message in messages %}
				{% if message.tags == 'error' %}
				<div style="z-index: 1000;"   class="alert alert-danger alert-dismissible fade show" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</div>
				{%else%}
				<div style="z-index: 1000;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					</div>
				{%endif%}
					
				{% endfor %}
			{%endif%}		
			
			  		<div class="row align-items-center">
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-left">
			  				<ul>
								{% if request.user.is_authenticated%}
			  					<li>
									<a href="#">signed in as {{request.user.username}}</a>
								</li>
								<li><a href="{% url 'accounts:logout_view' %}">logout</a></li>
								{% else %}
			  					<li><a href="{% url 'accounts:login_view' %}">login</a></li>
								<li><a href="{% url 'accounts:signup_view' %}">register</a></li>
								{% endif %}
			  				</ul>			
			  			</div>
			  			<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
			  			</div>
			  		</div>			  					
					</div>
				</div>
				<div class="container main-menu">
					<div class="row align-items-center justify-content-between d-flex">
				     
						<div id="logo">
				        <a href="{% url 'website:index'  %}"><img src="{% static 'img/logo.png' %}" alt="" title="" /></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li><a href="{% url 'website:index'  %}">Home</a></li>
				          <li><a href="{% url 'website:about'  %}">About</a></li>
						  <li><a href="{%url 'blog:index' %}">Blog</a></li>
				          <li class="menu-has-children"><a href="">Pages</a>
				            <ul>
				            	  <li><a href="elements.html">Elements</a></li>
						          <li class="menu-has-children"><a href="">Level 2 </a>
						            <ul>
						              <li><a href="#">Item One</a></li>
						              <li><a href="#">Item Two</a></li>
						            </ul>
						          </li>					                		
				            </ul>
				          </li>					          					          		          
				          <li><a href="{% url 'website:contact'  %}">Contact</a></li>
				        </ul>
				      </nav><!-- #nav-menu-container -->					      		  
					</div>
				</div>
			</header><!-- #header -->
            {% block content %}
            {% endblock %}


            <!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">

					<div class="row">
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>About Agency</h6>
								<p>
									The world has become so fast paced that people don’t want to stand by reading a page of information, they would much rather look at a presentation and understand the message. It has come to a point 
								</p>
							</div>
						</div>
						<div class="col-lg-3 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Navigation Links</h6>
								<div class="row">
									<div class="col">
										<ul>
											<li><a href="#">Home</a></li>
											<li><a href="#">Feature</a></li>
											<li><a href="#">Services</a></li>
											<li><a href="#">Portfolio</a></li>
										</ul>
									</div>
									<div class="col">
										<ul>
											<li><a href="#">Team</a></li>
											<li><a href="#">Pricing</a></li>
											<li><a href="#">Blog</a></li>
											<li><a href="#">Contact</a></li>
										</ul>
									</div>										
								</div>							
							</div>
						</div>							
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Newsletter</h6>
								<p>
									For business professionals caught between high OEM price and mediocre print and graphic output.									
								</p>								
								<div id="mc_embed_signup">
									<form  action="{% url 'website:news_letter'%}" method="post" class="subscription relative">
										{% csrf_token %}
										<div class="input-group d-flex flex-row">
											<input name="email" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
											<button type="submit" class="btn bb-btn"><span class="lnr lnr-location"></span></button>		
										</div>									
										<div class="mt-10 info"></div>
									</form>
								</div>
							</div>
						</div>
						<div class="col-lg-3  col-md-6 col-sm-6">
							<div class="single-footer-widget mail-chimp">
								<h6 class="mb-20">InstaFeed</h6>
								<ul class="instafeed d-flex flex-wrap">
									<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
									<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
								</ul>
							</div>
						</div>						
					</div>

					<div class="row footer-bottom d-flex justify-content-between align-items-center">
						<p class="col-lg-8 col-sm-12 footer-text m-0"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
						<div class="col-lg-4 col-sm-12 footer-social">
							<a href="#"><i class="fa fa-facebook"></i></a>
							<a href="#"><i class="fa fa-twitter"></i></a>
							<a href="#"><i class="fa fa-dribbble"></i></a>
							<a href="#"><i class="fa fa-behance"></i></a>
						</div>
					</div>
				</div>
			</footer>
			<!-- End footer Area -->
			{% compress js  %}

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
 			<script src="{% static 'js/jquery-ui.js' %}"></script>					
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<!-- <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script> -->
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>						
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>					
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>							
			<!-- <script src="{% static 'js/mail-script.js' %}"></script>	 -->
			<script src="{% static 'js/main.js' %}"></script>
			<!-- <script src="{% static 'js/404-page.js' %}"></script>	 -->
			 {% endcompress%}

		</body>
	</html>

website/templates/commingsoon.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Material Design for Bootstrap</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/commingsoon.min.css'%}" />
</head>
<body>
  <!--Main Navigation-->
  <header>
    <!-- Intro settings -->
    <style>
      /* Default height for small devices */
      #intro,body,html,header {
        height: 100%;
        /* Margin to fix overlapping fixed navbar */
      }
      
    </style>

   

    <!-- Background image -->
    <div id="intro" class="p-5 text-center bg-image shadow-1-strong"
      style="background-image: url('{% static "img/d1.jpg" %}');">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.7);">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white px-4" data-mdb-theme="dark">
            <h1 class="mb-3">Coming Soon!</h1>

            <p>We're working hard to finish the development of this site.</p>

          </div>
        </div>
      </div>
    </div>
    <!-- Background image -->
  </header>

</body>
</html>

website/templates/contact.html
	{%extends 'base.html'%}
	{% load static %}
{%block content%}
				<!-- start banner Area -->
			<section class="relative about-banner">	
				<div class="overlay overlay-bg"></div>
				<div class="container">	
						
					<div class="row d-flex align-items-center justify-content-center">
						<div class="about-content col-lg-12">
							<h1 class="text-white">
								Contact Us				
							</h1>	
							<p class="text-white link-nav"><a href="index.html">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="contact.html"> Contact Us</a></p>
						</div>	
					</div>
				</div>
				
			</section>
			<!-- End banner Area -->				  

			<!-- Start contact-page Area -->
			<section class="contact-page-area section-gap">
				<div class="container">
					<div class="row">
						<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
						<div class="col-lg-4 d-flex flex-column address-wrap">
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-home"></span>
								</div>
								<div class="contact-details">
									<h5>Binghamton, New York</h5>
									<p>
										4343 Hinkle Deegan Lake Road
									</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-phone-handset"></span>
								</div>
								<div class="contact-details">
									<h5>00 (958) 9865 562</h5>
									<p>Mon to Fri 9am to 6 pm</p>
								</div>
							</div>
							<div class="single-contact-address d-flex flex-row">
								<div class="icon">
									<span class="lnr lnr-envelope"></span>
								</div>
								<div class="contact-details">
									<h5>support@colorlib.com</h5>
			
									<p>Send us your query anytime!</p>
								</div>
							</div>														
						</div>
						<div class="col-lg-8">
							<form class="form-area contact-form text-right" id="myForm" action="{% url 'website:contact' %}" method="post">
								{% csrf_token %}
								<div class="row">	
									<div class="col-lg-6 form-group">
										{% if request.user.is_authenticated%}
										<input name="name" placeholder="Enter your username"
										 onfocus="this.placeholder = ''" hidden
										 onblur="this.placeholder = 'Enter your name'" 
										 class="common-input mb-20 form-control" required="" type="text"
										 value="{{request.user.username}}"
										 >

										<input name="email" placeholder="Enter email address"
										 pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$"
										  onfocus="this.placeholder = ''" 
										  onblur="this.placeholder = 'Enter email address'" 
										  class="common-input mb-20 form-control" required="" type="email"  hidden
										  value="{{request.user.email}}">
										{% else%}
										<input name="name"  value="this is a test" placeholder="Enter your name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required="" type="text">
										<input name="email" placeholder="Enter email address" pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required="" type="email">
										{% endif %}

										<input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control"  type="text">
									</div>
									<div class="col-lg-6 form-group">
										<textarea class="common-textarea form-control" name="message" placeholder="Enter Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>				
										
									</div>
									<div class="col-lg-12">
									{{form.captcha}}
										<div class="alert-msg" style="text-align: left;"></div>
										<button type="submit" class="genric-btn primary" style="float: right;">Send Message</button>											
									</div>
								</div>
							</form>	
						</div>
					</div>
				</div>	
			</section>
			
			<!-- End contact-page Area -->
{%endblock%}

website/templates/latest-blog-posts.html
{% load static%}
<section class="recent-blog-area section-gap">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="menu-content pb-60 col-lg-9">
                <div class="title text-center">
                    <h1 class="mb-10">Latest from Our Blog</h1>
                    <p>With the exception of Nietzsche, no other madman has contributed so much to human sanity as has.</p>
                </div>
            </div>
        </div>							
        <div class="row">
            <div class="active-recent-blog-carusel">
                {% for post in posts%}
                <div class="single-recent-blog-post item">
                    <div class="thumb">
                        <img style="max-width:345px;max-height:255px"  class="img-fluid" src="{{post.image.url }}" alt="">
                    </div>
                    <div class="details">
                        <div class="tags">
                            <ul>
                                {% for cat in post.category.all%}
                                <li>
                                    <a href="{% url 'blog:blog_cate' cat.name%}">{{cat.name}}</a>
                                </li>
                                {%endfor%}
                                										
                            </ul>
                        </div>
                        <a href="{% url 'blog:blog_single' post.id%}"><h4 class="title">{{post.title}}</h4></a>
                        <p>
                            {{post.content|truncatechars:100}}
                        </p>
                        <h6 class="date">{{post.updated_date|date:"d M Y"}}</h6>
                    </div>	
                </div>
                {% endfor%}
               													

            </div>
        </div>
    </div>	
</section>